### ISSUE TITLE
iPad 适配问题

### ISSUE THREAD

**Issue by NN708** [HeraldStudio/herald-web#11]
iPad 上访问目前是按照手机显示的，巨大无比……希望做一下适配
![cb59973d-0c52-4b36-b1cb-445ac639f457](https://user-images.githubusercontent.com/20534082/51227416-2eefdc80-198f-11e9-9fa8-d2281b3f9fde.jpeg)

**Comment by rikumi** [comment]
元旦前上线了针对移动端的 viewport 配置，实现对移动端定宽缩放适配，误伤到了 iPad，考虑下怎么解决

**Comment by NN708** [comment]
我个人感觉缩放适配是不是不太好……例如一些屏幕较宽的手机或手机横屏浏览课程表时，如果横向拉伸处理感觉看起来比较美观，但缩放适配就显得比较拥挤

**Comment by rikumi** [comment]
之前觉得应该完全禁止缩放适配，因为用户买大屏手机并不是想让字变大，而是想显示更多的内容。

然而问题是现在市场上安卓机的 DPI 都很不标准，很多大屏手机的出厂 DPI 故意调小，以给人一种显示区域很大的错觉，导致很多设备明明屏幕宽度相差不大，显示的尺寸大小却差异很大。

因此认为对宽度低于 480 逻辑像素的设备按 400px 做缩放适配还是比较有必要的。

**Comment by rikumi** [comment]
修改已发布到现网，可尝试验证。

**Comment by NN708** [comment]
这样改确实比较合适，对像素较低的设备仍然采用缩放。非常感谢。
