### ISSUE TITLE
希望能有 显示时间冲突的课程 的解决方案

### ISSUE THREAD

**Issue by Sciroccogti** [HeraldStudio/herald-web#12]
目前的情况是，新选的课程会在课表上盖过原有的同时段课程

**Comment by rikumi** [comment]
求个截图，为什么同一周的课还会有时间冲突🤔

**Comment by Sciroccogti** [comment]
菜鸡转系生的补修课。。

![image](https://user-images.githubusercontent.com/32357397/53961961-da621580-4124-11e9-8ca3-29f7f257ebeb.png)

而其实**计算机科学基础**覆盖了一节**模电**和**电磁场与电磁波**

**Comment by Sciroccogti** [comment]
![5B38C7AD-FF56-4D2E-A5D6-5153FC561DC5](https://user-images.githubusercontent.com/32357397/54097708-4b871e80-43ec-11e9-8836-9bba20809a47.png)

**Comment by rikumi** [comment]
添加了课程点选偏移，现在所有的课程方块背景色均为半透明白色，点击课程方块将会高亮、向左上方偏移并置顶2秒，2秒内可以点击查看被覆盖的课程。

**Comment by Sciroccogti** [comment]
非常感谢！
