### ISSUE TITLE
增加空教室后标签显示不全的问题

### ISSUE THREAD

**Issue by NN708** [HeraldStudio/herald-web#13]
增加空教室功能后，第4排有4个图标，在屏幕较窄的手机及竖屏的平板电脑导致显示不全标签。是否考虑调整一下布局？
![A1649215-95D2-4837-9BB7-BC1720308C80](https://user-images.githubusercontent.com/20534082/55222080-efbef100-5245-11e9-9270-f92b4d067f27.jpeg)
![208C7BB5-F086-4574-BC9B-B8F5222F804E](https://user-images.githubusercontent.com/20534082/55222081-efbef100-5245-11e9-8c86-ae30ce4eb6e3.jpeg)

**Comment by rikumi** [comment]
已变更：「App」入口已移至 Dashboard 顶部。(94e6249)
