### ISSUE TITLE
课表无法显示完整信息

### ISSUE THREAD

**Issue by tusooa** [HeraldStudio/herald-web#2]
如图。只有时间长的课才能显示得比较完整。体验很不好。
![timetable](https://user-images.githubusercontent.com/299873/38163347-1f636fec-3525-11e8-8207-46a6fe148da4.PNG)
考虑：
- 增大表格大小
- 提供悬浮框/点击弹出框(类似之前的App)
- 根据一定规则简化课程/教室名称(例如:九龙湖教三-101 -> J3-101) (复杂)
- 缩减无课日的列宽

**Comment by rikumi** [comment]
历史 issue，暂时认为已解决。如果仍有问题可新开 issue。
