### ISSUE TITLE
课表学期选择存在 bug

### ISSUE THREAD

**Issue by NN708** [HeraldStudio/herald-web#3]
当处于列表中第一个学期时再按下“上个学期”时，学期变空，无法正常切换到最后一个学期

![tim 20180623153947](https://user-images.githubusercontent.com/20534082/41807113-26e7d4b0-76fc-11e8-906d-e10e324ad8e0.png)
![tim 20180623154016](https://user-images.githubusercontent.com/20534082/41807117-2d9b9256-76fc-11e8-8327-b1964fd7c105.png)

**Comment by Sciroccogti** [comment]
另：
从列表视图切换回周视图的时候无法回到原显示学期（也许是因为考试周的尴尬时间点？）

**Comment by rikumi** [comment]
已解决，感谢提议
