### ISSUE TITLE
课表预测bug（？）

### ISSUE THREAD

**Issue by Sciroccogti** [HeraldStudio/herald-web#4]
学号前五位：04217（讲真是**信息学院**）
查到了很多显然是**医学院**的课
*怀疑是把`042`视为了`420`？

**Comment by rikumi** [comment]
不能复现，请检查
<img width="640" alt="xnip2018-08-16_00-53-25" src="https://user-images.githubusercontent.com/5051300/44161078-d28e4580-a0ee-11e8-8a9d-2cb1abea1d6f.png">

**Comment by Sciroccogti** [comment]
@rikumi 学期设置为`17-18-3`时会出现这种情况
![screenshot_2018-08-16-10-52-54-142_cn myseu heral](https://user-images.githubusercontent.com/32357397/44184665-ad2b2700-a142-11e8-8b43-fcc72d18cbf5.png)

**Comment by rikumi** [comment]
看样本容量明显比其他课少一位数，应该是转系生的锅，是有很多医转信息的吧……

简单说一下目前版本课表统计的原理，其实是在用户查询成绩的时候，从查到的成绩数据中取用户一年内上过的课程，将**课程本身**和**用户当前的院系**、**上这门课时的年级和学期**在数据库中建立关联，同时计算为一个样本容量，并和现有的平均成绩按样本容量加权，算出一个新的平均值。

经过长期试验，发现这样的数据来源其实是更新很快的。所以我刚刚把课表统计数据的过期速度从6个月降到了1个月，同时不仅课程本身过期，现在课程和院系的关联关系也会过期，从现在算起1个月之后，现在存在的数据都会被完全淘汰掉，数据量会逐渐收敛下来，转系生的干扰也会尽可能减小。

**Comment by Sciroccogti** [comment]
@rikumi 感谢。。这个“bug”真的是很有趣了2333
